### ISSUE TITLE
There seems a problem with the 4.4 version.

### ISSUE THREAD

**Issue by ShileiCao** [mcuntz/ncvue#7]
when i run ncvue 4.4, a bug has appeared:
 
 File "/public/home/anaconda3/envs/pangu1/lib/python3.9/site-packages/ncvue/ncvue.py", line 137, in ncvue
    top.tk.call('source', bundle_dir + '/../themes/azure-2.0/azure.tcl')
_tkinter.TclError: couldn't read file "/public/home/anaconda3/envs/pangu1/lib/python3.9/site-packages/ncvue/../themes/azure-2.0/azure.tcl": no such file or directory

**Comment by mcuntz** [comment]
Sorry, looks like I did an error in packaging. It is corrected now: v4.4.1
Works already on PyPI and is committed to Anaconda. Needs a bit of time until it is rebuilt. I will check that tomorrow noon (in 12 h).

**Comment by mcuntz** [comment]
Checked on Windows as well. Seems to work for PyPI and Anaconda with version v4.4.1.

**Comment by ShileiCao** [comment]
ok. It's already solved.
